---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: daily

allow:
- dependency-type: "direct"
  update-type: "minor"
- dependency-type: "direct"
  update-type: "patch"