version: '3.5'

networks:
  main:
    name: Network_Souffle

services:
  minitwit.server:
    build:
      context: ./MiniTwit
      dockerfile: Dockerfile
    container_name: Souffle-Server
    ports:
      - "5000:80"
    networks:
      - main
    depends_on:
      - grafana
      - prometheus

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - main

  grafana:
    image: grafana/grafana:9.4.3
    ports:
      - "3000:3000"  
    networks:
      - main