version: '3.5'

networks:
  main:
    name: network_souffle

services:
  minitwit.server:
    build:
      context: ../..
      dockerfile: MiniTwit/Server/Dockerfile
    image: subjective0/minitwit-souffle
    container_name: souffle-server
    ports:
      - "3005:80"
    networks:
      - main
    depends_on:
      - grafana
      - prometheus

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - main

  grafana:
    image: grafana/grafana:9.4.3
    ports:
      - "3000:3000"  
    networks:
      - main