---
name: Continuous Deployment

on:
  push:
    # Run workflow every time something is pushed to the main branch
    branches:
      - main

jobs:
  image-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./MiniTwit

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and push minitwit-souffle
        uses: docker/build-push-action@v2
        with:
          context: ./MiniTwit
          file: MiniTwit/MiniTwit/Server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/minitwit-souffle:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/minitwit-souffle:webbuildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/minitwit-souffle:webbuildcache,mode=max

      - name: Build and push minitwit-db
        uses: docker/build-push-action@v2
        with:
          context: ./MiniTwit
          file: MiniTwit/MiniTwit/Server/Dockerfile.database
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/minitwit-db:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/minitwit-db:mysqlbuildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/minitwit-db:mysqlbuildcache,mode=max
  
  deploy:
    runs-on: ubuntu-latest
    needs: image-build
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/minitwit.key
          chmod 600 ~/.ssh/minitwit.key
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Server
        run: >
          ssh $SSH_USER@$SSH_HOST
          -i ~/.ssh/minitwit.key -o StrictHostKeyChecking=no
          "docker stop minitwit-souffle &&
          docker rm minitwit-souffle &&
          docker pull $DOCKER_USERNAME/minitwit-souffle:latest &&
          docker run -d --name minitwit-souffle -p 5000:80 $DOCKER_USERNAME/minitwit-souffle:latest"
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

      - name: SSH-Compose
        # You may pin to the exact commit or the version.
        # uses: matiasnu/github-action-ssh-docker-compose@d2e13949c92cb86a69ea36e83ebaa01d6d01de9c
        uses: matiasnu/github-action-ssh-docker-compose@v2.0.1
        with:
          # Private SSH key used for logging into remote system.
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Remote host name.
          ssh_host: ${{ secrets.SSH_DB_HOST }}
          # Remote user name.
          ssh_user: ${{ secrets.SSH_USER }}
          # Docker compose file to use
          docker_compose_filename: MiniTwit/docker-compose-monitoring.yml
