name: .Net Format
on: pull_request
jobs:
  dotnet-format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./MiniTwit
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Add dotnet-format problem matcher
        uses: xt0rted/dotnet-format-problem-matcher@v1.2.0

      - name: Restore dotnet tools
        uses: xt0rted/dotnet-tool-restore@v1.0.1

      - name: Run dotnet format
        run: dotnet format ./MiniTwit.sln
