---
name: Build LaTeX document

on:
  push:
    # Run workflow every time something is pushed to the main branch
    branches:
      - main
    paths:
      - 'Report/**'
  # Run workflow manually
  workflow_dispatch:
    inputs:


permissions:
  contents: write
  pull-requests: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:
          # Fetch all history for all tags and branches
          fetch-depth: 0
      
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Report/main.tex
          working_directory: Report

      - run: "ls -l Report"
      - run: "ls"
      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add Report/main.pdf
          git commit -m "Update PDF"
          git push